version: "3"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        - target=dev
    volumes:
      - ./app:/app
    ports:
      - "18000:80"
