version: "3"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        - target=dev
    environment:
      CHEKI_DB_HOST: cheki-db
      CHEKI_DB_PORT: 3306
      CHEKI_DB_DATABASE: cheki

    volumes:
      - ./app:/app
    ports:
      - "18000:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: cheki-db
    volumes:
      - db-data:/var/lib/mysql
      - ./app/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=cheki
    ports:
      - "33306:3306"

volumes:
  db-data:
