name: test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - uses: actions/checkout@v3

    - run: cd app && go test -coverprofile=coverage.out

    - name: report coverage
      uses: k1LoW/octocov-action@v0
